In [2]:
"""
Name: Abhinav Kamboj
Subject: Cloud Computing Lab
Assignment: 1 & 2
"""
import numpy as np
from collections import defaultdict

In [3]:
# Create Large Data File

with open("large_data.txt", "w") as f:
    for _ in range(20000):
        row = np.random.randint(0, 100, 10000)
        f.write(" ".join(map(str, row)) + "\n")

print("File created successfully!")

File created successfully!


In [4]:
#Shift Subsequent Rows
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
shifted_matrix = np.roll(matrix, -1, axis=0)
print("Original Matrix:\n", matrix)
print("Shifted Matrix:\n", shifted_matrix)

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shifted Matrix:
 [[4 5 6]
 [7 8 9]
 [1 2 3]]


In [6]:
#Group Similar Elements

arr = [1,2,2,3,3,3,4]

group = defaultdict(list)

for i in arr:
    group[i].append(i)

print(list(group.values()))

[[1], [2, 2], [3, 3, 3], [4]]


In [7]:
#Matrix Addition & Subtraction
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("Addition:\n", A+B)
print("Subtraction:\n", A-B)

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]


In [10]:
#n×n Matrix Condition
n = 4
valid = True
for i in range(n):
        for j in range(n):
            matrix[i][j] = (i + j) * 2
print(matrix)

[[ 0  2  4  6]
 [ 2  4  6  8]
 [ 4  6  8 10]
 [ 6  8 10 12]]


In [12]:
#Row wise addition in tupple matrix
matrix = ((1,2,3),(4,5,6),(7,8,9))

result = [sum(row) for row in matrix]

print(result)

[6, 15, 24]
